name: reports-system
version: '${project.version}'
main: xyz.joaomadeira.reportsSystem.ReportsSystem

commands:
  report:
    description: Report a player
    usage: /<command> <player> <reason>
  reports:
    description: Open the staff reports panel
    usage: /<command>
